# =====================
# Site settings
# =====================
title: ElModdy
email: your-email@example.com
description: >-
  My personal site using the Console Jekyll theme.
baseurl: ""                    # Subpath of your site, e.g., /blog
url: "https://ElModdy.github.io"  # Full site URL

# =====================
# Build settings
# =====================
markdown: kramdown
kramdown:
  math_engine: mathjax          # Pass math to MathJax
  input: GFM                    # GitHub Flavored Markdown

theme: null                     # Must be null when using remote_theme
remote_theme: https://github.com/riggraz/no-style-please
# =====================
# Plugins
# =====================
plugins:
  - jekyll-remote-theme         # Required to render remote themes locally

# =====================
# Permalinks
# =====================
permalink: /:title/

# =====================
# Defaults
# =====================
defaults:
  # Default layout for posts
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

  # Enable MathJax on all pages
  -
    scope:
      path: ""
    values:
      mathjax: true

# =====================
# Exclude files/folders from build
# =====================
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle
  - README.md

tracking:
  script_src:
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

csp_extra: "script-src 'self' https://cdn.jsdelivr.net 'unsafe-inline'; style-src 'self' https://cdn.jsdelivr.net; font-src 'self' https://cdn.jsdelivr.net;"
